# Generated by Django 4.1.5 on 2023-02-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newtask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("direccion", models.CharField(max_length=80)),
                ("ciudad", models.CharField(max_length=30)),
                ("comuna", models.CharField(max_length=20)),
                ("zona", models.CharField(max_length=20)),
                ("tarea", models.CharField(max_length=30)),
                ("estado", models.CharField(max_length=15)),
                ("solot", models.IntegerField()),
                ("idSGA", models.IntegerField()),
                ("numServicio", models.IntegerField()),
                ("fechaAtencion", models.DateField()),
                ("horaAtencion", models.DateTimeField()),
            ],
        ),
    ]
